ALX task on python_exception
